export const GET_PAGE_REQUEST = 'GET_PAGE_REQUEST';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';

export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_FILTER = 'SET_FILTER';
export const SET_SORT_FIELD = 'SET_SORT_FIELD';